### ISSUE TITLE
SSH error

### ISSUE THREAD

**Issue by coco1979ka** [nathanleclaire/dockerfiles#1]
First thanks for this great idea how to provision a docker-machine. Unfortunately when I tried it with my local docker-machine (virtualbox), I get an error when the bootstrap is applied:

TASK: [Install desired packages] *********************************************\* 
fatal: [localhost] => SSH encountered an unknown error during the connection.

Any ideas why this happens?

**Comment by nathanleclaire** [comment]
IIRC Vbox SSH port forwarding to localhost did not play well with the Ansible bootstrap
